## Exercise 2

**This class is Homework 1, questions 2 and 3.** By the end you will have coded the
three information criteria yourself and compared them with the top-down sequence.

Note the assignment rule: you are **not allowed to use built-in functions** for these,
so everything here is written from scratch with `numpy`.

#### Important linear algebra operations

The following goes through the most popular linear algebra operations that we will use in the exercises.

In [1]:
import numpy as np

A = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
B = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

C = np.array([[5, 6, 7], 
            [8, 3, 1], 
            [6, 3, 8]])

Tranpose of a vector: $B^\prime $

In [2]:
B_transpose = B.T
B_transpose

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

Product of two vectors/matrices: $A \cdot B^\prime$

In [3]:
AB_transpose = A @ B_transpose
AB_transpose

array([[285]])

Inverse of a matrix: $C^{-1}$

In [4]:
C_inv = np.linalg.inv(C)
C_inv

array([[-0.10447761,  0.13432836,  0.07462687],
       [ 0.28855721,  0.00995025, -0.25373134],
       [-0.02985075, -0.10447761,  0.1641791 ]])

Determinant of a matrix: $\det(C)$

In [5]:
C_det = np.linalg.det(C)
C_det

np.float64(-201.0)

Trace of a matrix: $tr(C)$

In [6]:
C_trace = np.trace(C)
C_trace

np.int64(16)

#### The information criteria

There are three common information criteria known as The Akaike Information Criterion (AIC), Hannan-Quin Criterion (HQC) and the Schwarz Information Criterion (SIC). 

The AIC is given as:

\begin{equation*}
    \text{AIC}(m) = \log\left(\det\left(\widetilde{\Sigma}_{u}(m)\right)\right) + \frac{2}{T}\left(mK^{2} + K\right)
\end{equation*}

where $\widetilde{\Sigma}_{u}(m)=T^{-1}\sum_{t=1}^{T}\hat{u}_{t}\hat{u}_{t}^{\prime}$ is the covariance matrix estimator for the least square residual, $\hat{u}_{t}$, at a given lag order, $m$. $K$ is the number of equations in the model and $T$ is the number of observations used. 

The HQC is given as:


\begin{equation*}
    \text{HQC}(m)=\log\left(\det\left(\widetilde{\Sigma}_{u}(m)\right)\right)+\frac{2\log(\log(T))}{T}\left(mK^{2}+K\right)
\end{equation*}

The SIC is given as:

\begin{equation*}
    \text{SIC}(m)=\log\left(\det\left(\widetilde{\Sigma}_{u}(m)\right)\right)+\frac{\log(T)}{T}\left(mK^{2}+K\right)
\end{equation*}

Your goal is to implement each information criteria and report the one number of lags that produces the smalles information criteria.

1. The following code generates an VAR(1) model with 2 variables. Make sure you understand how the VAR(1) process is generated. 

In [1]:
%reset -f #We force wipe all previous variables

import numpy as np
import pandas as pd

#set amount of decimals
pd.set_option('display.float_format', '{:.4f}'.format)

np.random.seed(1)

# Parameters
N = 100  # Number of observations
rho1 = np.array([[0.8, 0],  # Autoregressive coefficient for lag 1
                 [0, 0.8]])

alpha = np.array([0, 0])  # Mean of the VAR process

sigma = np.array([[1, 0],  # Covariance matrix of white noise
                  [0, 1]])

y = np.zeros((2, N))

# Generate white noise
epsilon = np.random.multivariate_normal([0, 0], sigma, N).T

# Generate the VAR(2) process
for t in range(1, N):
    y[:, t] = alpha + rho1 @ y[:, t-1]  + epsilon[:, t]

y = y.T


Don't know how to reset  #we, please run `%reset?` for details
Don't know how to reset  force, please run `%reset?` for details
Don't know how to reset  wipe, please run `%reset?` for details
Don't know how to reset  all, please run `%reset?` for details
Don't know how to reset  previous, please run `%reset?` for details
Don't know how to reset  variables, please run `%reset?` for details


2. Fill out the missing parts of the function "pfind(y, max)" 


Hint: Remember that if we estimate the companion form of the VAR(m) model, $Y_{t}=\beta X_{t}+u_{t}$, then we have that $u_{t}=Y_{t}-\beta X_{t}$, $\beta=\left(XX^{\prime}\right)^{-1}\left(YX^{\prime}\right)$ and $\Sigma_{u}=\frac{1}{T}uu^{\prime}$

In [64]:
def pfind(y, pmax):
    t, K = y.shape

    # Construct regressor matrix and dependent variable
    XMAX = np.ones((1, t - pmax))
    
    for i in range(1, pmax + 1):
        XMAX = np.vstack([XMAX, y[pmax - i:t - i, :].T])

    Y = y[pmax:t, :].T

    aiccrit = np.zeros((pmax + 1, 1))
    hqccrit = np.zeros((pmax + 1, 1))
    siccrit = np.zeros((pmax + 1, 1))

    # Evaluate criterion for p = 0,...,pmax
    for j in range(0, pmax + 1):
        m = # Fill in
        T = # Fill in
        X = # Fill in

        B = # Fill in

        SIGMA = # Fill in

        aiccrit[j] = # Fill in
        hqccrit[j] = # Fill in
        siccrit[j] = # Fill in

    # Retrieve the lag with the lowest information criteria
    aichat = # Fill in
    hqchat = # Fill in
    sichat = # Fill in

    infomat = np.hstack([siccrit, hqccrit, aiccrit])
    m = np.arange(0, pmax + 1).reshape(-1, 1)
    imat = np.hstack([m, infomat])

    LagInformationValue = pd.DataFrame(imat, columns=['Lag', 'SIC', 'HQ', 'AIC'])
    OptimalLag = pd.DataFrame([[sichat, hqchat, aichat]], columns=['SIC', 'HQ', 'AIC'])

    return LagInformationValue, OptimalLag


LagInformationValue, OptimalLag = pfind(y,12)


In [ ]:
LagInformationValue

In [ ]:
OptimalLag

If implemented correctly, the function should output the following values:

| **Lag** | **SIC**  | **HQ**   | **AIC**  |
|---------|----------|----------|----------|
| 0.0000  | 1.3068   | 1.2732   | 1.2505   |
| 1.0000  | -0.2371  | -0.3379  | -0.4060  |
| 2.0000  | -0.1492  | -0.3173  | -0.4307  |
| 3.0000  | 0.0280   | -0.2073  | -0.3661  |
| 4.0000  | 0.2000   | -0.1026  | -0.3067  |
| 5.0000  | 0.3634   | -0.0064  | -0.2559  |
| 6.0000  | 0.4971   | 0.0600   | -0.2348  |
| 7.0000  | 0.6766   | 0.1723   | -0.1680  |
| 8.0000  | 0.7884   | 0.2168   | -0.1688  |
| 9.0000  | 0.9508   | 0.3120   | -0.1190  |
| 10.0000 | 1.1389   | 0.4329   | -0.0435  |
| 11.0000 | 1.2849   | 0.5116   | -0.0101  |
| 12.0000 | 1.4125   | 0.5720   | 0.0049   |


3. Consider what the maximum lag length should be. What is the tradeoff when setting a higher maximum lag length?

4. Try changing the seed. Does the optimal information criteria always give the same conclusion? What if the number of observations are changed?

5. Read page 58-60 in Kilian and Lütkepohl (2017). How consistent is the information criteria for the true lag length and how consistent are they in small samples?

6. Expand the VAR(1) process to a VAR(2) process by making $\rho_{2}=\left[\begin{array}{cc}
0.15 & 0\\
0 & 0.15
\end{array}\right]$. Make sure the code still works. Are the conclusions above still the same?

In [75]:
## Insert code for an AR(2) and perform optimal lag order searc

Instead of calculating the information criteria, one can perform a top-down sequential test. Letting $A_t$ denote the coefficient at a given lag length, Kilian and Lütkepohl (2017), p. 51, notes that:

One possible sequential procedure involves testing the sequence of null hypotheses:
$H_{0}: A_{p_{\text{max}}} = 0$ vs. $H_{1}: A_{p_{\text{max}}} \neq 0$, 
$H_{0}: A_{p_{\text{max}}-1} = 0$ vs. $H_{1}: A_{p_{\text{max}}-1} \neq 0$, etc., 
until $H_{0}: A_{1} = 0$ vs. $H_{1}: A_{1} \neq 0$. The procedure continues, 
as long as the null hypothesis is not rejected. If there is a rejection, 
the testing procedure terminates, and we conclude that we require as many lags 
as maintained under the last alternative hypothesis. If none of the null hypotheses 
can be rejected, we conclude that $p = 0$. Such procedures are known as 
top-down or general-to-specific procedures because they start with the largest model 
and sequentially reduce the lag order of the model. In implementing this sequential test, 
the usual Wald or LR tests for parameter restrictions can be employed. 
For example, the LR statistic for testing a VAR($m$) against a VAR($m + 1$) has the form

\begin{equation*}
LR(m) = T \left[ \log(\det(\widetilde{\Sigma}_{u}(m))) - \log(\det(\widetilde{\Sigma}_{u}(m+1))) \right]
\end{equation*}

where

\begin{equation*}
\widetilde{\Sigma}_{u}(m) = T^{-1} \sum_{t=1}^{T} \hat{u}_{t} \hat{u}_{t}'
\end{equation*}

is the ML estimator of the residual covariance matrix for a VAR($m$) model. 
One also could alternatively use the LS residuals $\hat{u}_{t}$. 
If $H_{0}: A_{m+1} = 0$ is tested against $H_{1}: A_{m+1} \neq 0$, 
the $LR(m)$ statistic has an asymptotic $\chi^{2}(K^{2})$ distribution under $H_{0}$.


7. Use the following code to perform a top-down testing sequence. What is the optimal number of lags? Is the result the same as when using the Information criteria?

In [ ]:
from scipy.stats import chi2

pmax = 12  # Set maximum lag order

def top_down(y, pmax):
    t, K = y.shape
    
    # Construct regressor matrix and dependent variable
    XMAX = np.ones((1, t - pmax))
    for i in range(1, pmax + 1):
        XMAX = np.vstack([XMAX, y[pmax - i:t - i, :].T])

    Y = y[pmax:t, :].T

    # Initialize Log Likelihood storage
    LL = []

    # Evaluate models for lag lengths from pmax down to 0
    for j in range(pmax, -1, -1):
        T = t - pmax
        X = XMAX[:j * K + 1, :]

        B = Y @ X.T @ np.linalg.inv(X @ X.T)
        SIGMA = (Y - B @ X) @ (Y - B @ X).T / T

        # Log-Likelihood
        LL.insert(0, [j, T * np.log(np.linalg.det(SIGMA))])

    LL = np.array(LL)

    # Initialize results table
    results = np.array([[0, LL[0, 1], 0, 0]])

    # Calculate LR test statistics and p-values
    for ii in range(pmax):
        lr_stat = LL[ii, 1] - LL[ii + 1, 1]
        p_value = 1 - chi2.cdf(lr_stat, K ** 2)
        results = np.vstack([results, [LL[ii + 1, 0], LL[ii + 1, 1], lr_stat, p_value]])

    # Convert results to a table
    table_lr = pd.DataFrame(results, columns=['Lag', 'Log. Likelihood', 'LR test', 'p-value'])

    return table_lr

top_down(y, pmax)


8. Currently, the code does not take into account a linear trend in the data. Account for this by adding a linear trend in pfind (and top_down if time) using the following code and change the function accordingly:

In [71]:
# XMAX = np.vstack([XMAX, np.arange(1, t - pmax + 1).reshape(1, -1)]) 

9. Did the results change?

10. At last, use the code you have written to answer **questions 2 and 3 of Homework 1**.

The homework VAR is not quite the model you have been simulating. From the assignment
hints, the system is

$$x = [\\,rfor,\\ lgdp,\\ pi,\\ dlrexc,\\ rdom\\,]$$

estimated on 1983Q1-2004Q4 together with a constant, a **linear trend**, and the dummies
`du93Q1`, `du92Q3` and `du95Q4`.

So the regressor matrix has two parts: a deterministic block that is the *same* for every
candidate lag order, and a lag block that grows with $m$. Only the second part changes as
you move down the table.

- Load the `result.csv` you produced in Exercise Class 1
- Extend `pfind` (and `top_down`) so the deterministic block is `[constant, dummies, trend]`
- Use `pmax = 4`: this is quarterly data, so four lags is one year
- What do the three criteria say? What does the top-down sequence say? Do they agree,
  and does the answer change if you set `pmax = 8` or `12`?

In [ ]:
from pathlib import Path

# result.csv is the file you produced in Exercise Class 1
CANDIDATES = [
    Path.cwd() / "result.csv",
    Path.cwd().parent / "Exercise Class 1" / "result.csv",
]
CSV = next((p for p in CANDIDATES if p.exists()), None)
if CSV is None:
    raise FileNotFoundError(
        "Could not find result.csv - run the Exercise Class 1 notebook first. Looked in:\n  "
        + "\n  ".join(str(p) for p in CANDIDATES)
    )

data = pd.read_csv(CSV)

ENDOG = ["rfor", "lgdp", "pi", "dlrexc", "rdom"]   # order matters, see the hints
DUMMIES = ["du93Q1", "du92Q3", "du95Q4"]

y = data[ENDOG].to_numpy()          # the K = 5 endogenous variables
dum = data[DUMMIES].to_numpy(float) # exogenous dummies for the deterministic block

print(f"T = {y.shape[0]} observations, K = {y.shape[1]} variables")

# Your turn: write pfind_det(y, pmax, dum) with the deterministic block
# [constant, dummies, linear trend] and report the optimal lag for pmax = 4.